SIMULATION_YEAR = 2022
LATITUDE = float
LONGITUDE = float
ALTITUDE = int
WEATHER_API_URL = str
TIMEZONE = str
DEMAND_PER_BUILDING_MWH_ANNUALLY = int
NUM_BUILDINGS = int

# pv params
SURFACE_TILT = int
SURFACE_AZIMUTH = int
PANEL_POWER_WATTS = int
NUMBER_OF_PANELS = int
INVERTER_EFFICIENCY = float
PANEL_TEMPERATURE_LOSS = float

# BESS_PARAMS
BESS_CAPACITY_MWH = float
BESS_POWER_MWH = float

# fuel params
KWH_IN_M3_OF_BIOGAS = float

# digester params
DIGESTER_CONSTANT_OUTPUT_MW = float
BIOGAS_BOILER_THERMAL_EFFICIENCY = float

# efficiencies
ELECTRICAL_EFFICIENCY = float
CHP_THERMAL_EFFICIENCY  = float